
import fetch from "node-fetch";

const API_BASE = "http://localhost:3002/v1/tool";

async function testDirective(lane, shouldPass) {
    console.log(`\nTesting Lane Enforcement: '${lane}' (Expected: ${shouldPass ? "PASS" : "FAIL"})...`);

    try {
        const res = await fetch(`${API_BASE}/core.create_directive`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                params: {
                    summary: `Verification Test: ${lane}`,
                    directive_type: "MANDATE",
                    priority: "P2",
                    owner_execution: lane,
                    acceptance_tests: ["Auto-generated by verify_lanes.js"]
                }
            })
        });

        const data = await res.json();

        if (res.ok && data.ok) {
            if (shouldPass) {
                console.log("✅ SUCCESS: Directive created as expected.");
            } else {
                console.error("❌ FAILURE: Directive should have been rejected but was created.");
                console.log("Response:", data);
            }
        } else {
            if (!shouldPass) {
                console.log("✅ SUCCESS: Directive correctly rejected.");
                console.log("Error:", data.error || data);
            } else {
                console.error("❌ FAILURE: Directive should have succeeded but failed.");
                console.error("Error:", data.error || data);
            }
        }

    } catch (err) {
        console.error("Network Error:", err.message);
        console.log("Ensure mcp-notion server is running on port 3002.");
    }
}

async function run() {
    console.log("=== CORE Lane Enforcement Verification ===");
    // Test 1: ARC (Should FAIL - Constraint Lane)
    await testDirective("ARC", false);

    // Test 2: LAW (Should FAIL - Constraint Lane)
    await testDirective("LAW", false);

    // Test 3: WAR (Should PASS - Execution Lane)
    await testDirective("WAR", true);

    // Test 4: RANDOM (Should PASS with Warning or just PASS, logic allows unknown but warns)
    // Logic says: if (!ALLOWED) return { pass: true, reason: warn }
    await testDirective("UNKNOWN_POD", true);
}

run();
